version: '2.1'
services:
   testfrontend:
     image: kvalitetsit/gooioidwsrest:1.1.14
     command:
      - "-config"
      - "/caddy/config.json"
     volumes:
      - ./frontend.json:/caddy/config.json
     ports:
      - 8080:80
   helloservice:
     image: kvalitetsit/rm-eboks-service:latest
     environment:
      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
   documenatation-and-test:
     image: kvalitetsit/rm-eboks-service-documentation:latest
     environment:
      - BASE_URL=/test
     ports:
      - 80:8080
