openapi: 3.0.0
info:
  title: Eboks Service
  description: Eboks Service
  version: "1.0.0"
  contact:
    email: development@kvalitetitsit.dk

servers:
  - url: '{protocol}://{environment}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      environment:
        enum:
          - localhost # Docker-compose setup
        default: localhost # Development
      port:
        enum:
          - 8080
        default: 8080
paths:
  /eboks-service/send:
    post:
      summary: Send eboks besked
      description: Send en besked til en persons eboks vha den angivne skabelon
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sendRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sendResponse'

  /eboks-service/templates:
    get:
      summary: Mail skabeloner
      description: Se navn og beskrivelse af konfigurerede mail skabeloner
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatesResponse'

components:
  responses:
    '400':
      description: "Bad Request. This could be because: * One of the required parameters/properties are missing or is empty <br> * Length of input is exceeding maximum length <br> (See a possible detailed error message in the in the response.)"
    '401':
      description: "Unauthorized. This could be because: <br> * The calling system has not been properly authenticated."
    '403':
      description: "Forbidden. This could be because: <br> * The requested information does not belong the organisation of the user <br> * The calling user does not have the required roles"

  schemas:
    sendResponse:
      type: object
      properties:
        message:
          type: string

    sendRequest:
      type: object
      required:
        - cpr
        - template
      properties:
        cpr:
          description: CPR nummer på modtageren
          type: string
        template:
          description: Navnet på den skabelon der skal anvendes
          type: string

    templatesResponse:
      type: array
      items:
        $ref: '#/components/schemas/templateResponse'

    templateResponse:
      type: object
      properties:
        name:
          type: string
        description:
          type: string